# Databricks notebook source
# MAGIC %md
# MAGIC # Deploy — NorthStar Brand Copilot (Databricks Apps, in-workspace)
# MAGIC In-workspace replacement for `deployment/deploy.sh` + the Asset Bundle. Uses the Apps REST
# MAGIC API directly (no local CLI, no `databricks bundle`). All values come from `../config`.
# MAGIC
# MAGIC What it does (what the bundle used to do):
# MAGIC 1. **Writes `agent_app/app.yaml`** with the real env values from `../config` (replaces the
# MAGIC    `perl` placeholder injection in deploy.sh).
# MAGIC 2. **Creates the app** with the same `resources` the bundle declared in `databricks.yml`
# MAGIC    (experiment, LLM + embedding endpoints, Genie space, Vector Search index, Lakebase,
# MAGIC    warehouse). This drives BOTH the `valueFrom` env resolution AND the service-principal
# MAGIC    resource grants — exactly like the bundle.
# MAGIC 3. **Deploys** from the workspace source path.
# MAGIC
# MAGIC **Prereqs:** setup/00–04 complete (experiment, VS index, Genie space, Lakebase instance +
# MAGIC schema all exist), and the project imported to `PROJECT_DIR`.

# COMMAND ----------
# MAGIC %run ../config

# COMMAND ----------
import time
from databricks.sdk.service.workspace import ImportFormat

# Required ids produced during setup — fail fast with a clear message if missing.
require("GENIE_SPACE_ID", GENIE_SPACE_ID)
require("EXPERIMENT_ID", EXPERIMENT_ID)

# COMMAND ----------
# 1. Write app.yaml with real env values (replaces deploy.sh's perl injection).
#    The app reads its runtime env from THIS file. `value_from` entries resolve against the
#    named app resources created in step 2 (experiment id, lakebase instance name).
APP_YAML = f"""# Generated by deployment/deploy — do not edit by hand. Edit ../config and re-run.
command: ["uv", "run", "start-server"]

env:
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  - name: MLFLOW_REGISTRY_URI
    value: "databricks-uc"
  - name: API_PROXY
    value: "http://localhost:8000/invocations"
  - name: CHAT_APP_PORT
    value: "3000"
  - name: CHAT_PROXY_TIMEOUT_SECONDS
    value: "300"
  - name: MLFLOW_EXPERIMENT_ID
    valueFrom: "experiment"
  # --- Agent configuration ---
  - name: MODEL_ENDPOINT
    value: "{MODEL_ENDPOINT}"
  - name: GENIE_SPACE_ID
    value: "{GENIE_SPACE_ID}"
  - name: VS_CATALOG
    value: "{CATALOG}"
  - name: VS_SCHEMA
    value: "{SCHEMA}"
  - name: WAREHOUSE_ID
    value: "{WAREHOUSE_ID}"
  # --- Lakebase long-term memory ---
  - name: LAKEBASE_INSTANCE_NAME
    valueFrom: "database"
  - name: EMBEDDING_ENDPOINT
    value: "{EMBEDDING_ENDPOINT}"
  - name: EMBEDDING_DIMS
    value: "{EMBEDDING_DIMS}"
"""

# Write into the workspace source tree so the deployment picks it up.
app_yaml_ws = f"{APP_SOURCE_PATH}/app.yaml"
w.workspace.upload(
    app_yaml_ws, APP_YAML.encode("utf-8"),
    format=ImportFormat.RAW, overwrite=True,
)
print("Wrote", app_yaml_ws)

# COMMAND ----------
# 2. Create the app with the same resources the bundle declared. Idempotent.
#    These resources both (a) satisfy the app.yaml `value_from` refs and (b) grant the
#    app's service principal access — the job deploy.sh delegated to the bundle.
# NOTE: the Apps REST API resource schema differs from the bundle (DAB) schema — it uses
# `experiment_id` and `space_id` (the bundle used `id`). Field names below are REST-API-correct.
app_resources = [
    {"name": "experiment",
     "experiment": {"experiment_id": EXPERIMENT_ID, "permission": "CAN_MANAGE"}},
    {"name": "llm",
     "serving_endpoint": {"name": MODEL_ENDPOINT, "permission": "CAN_QUERY"}},
    {"name": "embedding",
     "serving_endpoint": {"name": EMBEDDING_ENDPOINT, "permission": "CAN_QUERY"}},
    {"name": "genie_space",
     "genie_space": {"space_id": GENIE_SPACE_ID, "permission": "CAN_RUN"}},
    {"name": "vector_index",
     "uc_securable": {"securable_full_name": VS_INDEX,
                      "securable_type": "TABLE", "permission": "SELECT"}},
    {"name": "database",
     "database": {"instance_name": LAKEBASE_INSTANCE,
                  "database_name": "databricks_postgres",
                  "permission": "CAN_CONNECT_AND_CREATE"}},
    {"name": "warehouse",
     "sql_warehouse": {"id": WAREHOUSE_ID, "permission": "CAN_USE"}},
]

app_body = {
    "name": APP_NAME,
    "description": "NorthStar Brand Copilot — CPG brand & sales assistant "
                   "(LangGraph + Genie + Vector Search + Lakebase)",
    "resources": app_resources,
}

try:
    w.api_client.do("GET", f"/api/2.0/apps/{APP_NAME}")
    print("App exists — updating resources:", APP_NAME)
    w.api_client.do("PATCH", f"/api/2.0/apps/{APP_NAME}", body=app_body)
except Exception:
    print("Creating app:", APP_NAME)
    w.api_client.do("POST", "/api/2.0/apps", body=app_body)

# Wait for the app compute to be ready before deploying code.
print("Waiting for app to be ready ...")
while True:
    app = w.api_client.do("GET", f"/api/2.0/apps/{APP_NAME}")
    state = (app.get("compute_status") or {}).get("state") or app.get("app_status", {}).get("state")
    if state in ("ACTIVE", "RUNNING", "STOPPED", None):
        break
    print("   ...", state)
    time.sleep(15)

# COMMAND ----------
# 3. Deploy the app source from the workspace path.
# The Apps deployment API expects the full filesystem path, which is the workspace path
# prefixed with /Workspace (config's APP_SOURCE_PATH is the bare /Users/... path).
deploy_source_path = "/Workspace" + APP_SOURCE_PATH
print("Deploying source from:", deploy_source_path)
dep = w.api_client.do(
    "POST", f"/api/2.0/apps/{APP_NAME}/deployments",
    body={"source_code_path": deploy_source_path, "mode": "SNAPSHOT"},
)
dep_id = dep.get("deployment_id")
print("deployment_id:", dep_id)

# Poll the deployment to completion.
print("Waiting for deployment ...")
while True:
    d = w.api_client.do("GET", f"/api/2.0/apps/{APP_NAME}/deployments/{dep_id}")
    st = (d.get("status") or {}).get("state", "UNKNOWN")
    if st in ("SUCCEEDED", "FAILED", "STOPPED"):
        print("   deployment:", st, (d.get("status") or {}).get("message", ""))
        break
    print("   ...", st)
    time.sleep(15)

# COMMAND ----------
# 4. App details.
app = w.api_client.do("GET", f"/api/2.0/apps/{APP_NAME}")
print("URL              :", app.get("url"))
print("SP client id     :", app.get("service_principal_client_id"))
print("status           :", (app.get("app_status") or {}).get("state"))
print("\nNEXT: run deployment/grant_resources to grant UC + warehouse + Lakebase table access.")
print("(The resource-level grants above are applied by the app create; grant_resources adds the")
print(" UC catalog/schema/table SELECT and Lakebase Postgres role that resources can't express.)")
